name: "📋 Documentation"
description: "Plantilla para solicitudes o mejoras en la documentación"
labels: [documentation]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Descripción de la mejora de la documentación"
      description: "Describe de forma clara qué parte de la documentación necesita ser mejorada o ampliada."
      value: "Escribe aquí la descripción de la mejora..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "🔄 ¿Por qué se necesita esta mejora?"
      description: "Explica por qué es importante actualizar o mejorar la documentación."
      value: "Escribe aquí la razón de la mejora..."
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: "🔮 ¿Qué información debería ser añadida o modificada?"
      description: "Detalla qué aspectos específicos de la documentación necesitan ser modificados o agregados."
      value: "Escribe aquí los detalles sobre la modificación..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Marca los puntos que sean relevantes para esta solicitud de documentación."
      options:
        - label: "La documentación está desactualizada o no es clara."
          required: true
        - label: "Se necesita añadir ejemplos o casos de uso."
          required: true
        - label: "Se deben corregir errores tipográficos o gramaticales."
          required: false
        - label: "Se debe agregar más información técnica detallada."
          required: false
