name: 🚀 New Feature Request
description: Plantilla para solicitudes de nuevas funcionalidades
title: "[FEATURE] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Descripción

        Describe de forma clara y concisa qué funcionalidad necesitas implementar.  
        Si es necesario, incluye cualquier detalle de contexto relevante para entender la tarea.

        **Fragmento relevante del código (si aplica):**

        ```js
        // TODO: Describe lo que hay que implementar o lo que falta.
        ```

  - type: markdown
    attributes:
      value: |
        ## ✅ Comportamiento esperado

        Describe el comportamiento esperado de la funcionalidad que se está implementando.  
        Incluye:
        - ¿Cómo debe funcionar esta funcionalidad?
        - ¿Qué debe ocurrir cuando el usuario interactúa con ella?
        - ¿Cómo debe reaccionar el sistema en caso de errores?

  - type: markdown
    attributes:
      value: |
        ## 💻 Entorno

        - **Componente(s):**  
        - **Framework o Biblioteca:**  
        - **Dependencias relevantes:**

  - type: markdown
    attributes:
      value: |
        ## 📎 Recursos adicionales

        Incluye enlaces a documentación, diagramas, enlaces relevantes o cualquier otro recurso que pueda ayudar a implementar esta funcionalidad.

  - type: checkboxes
    attributes:
      label: ✅ Checklist
      description: Marca cada punto una vez completado.
      options:
        - label: Se ha implementado la funcionalidad requerida.
        - label: Se han cubierto todos los casos de uso esperados.
        - label: Se han manejado los errores correctamente.
        - label: Se ha probado la funcionalidad en el entorno adecuado.
        - label: La funcionalidad está documentada (si aplica).
